'use strict';

// SemVer source-of-truth handling. VERSION (plugin root) is the only writable
// version; sync() fans it out to plugin.json + marketplace.json. bump() applies
// a major/minor/patch increment. Pure string helpers; the caller writes files.

const fs = require('fs');
const path = require('path');

function parse(version) {
  const m = String(version).trim().match(/^(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z.-]+))?$/);
  if (!m) {
    throw new Error(`Invalid SemVer: ${version}`);
  }
  return { major: +m[1], minor: +m[2], patch: +m[3], prerelease: m[4] || null };
}

function format({ major, minor, patch, prerelease }) {
  const base = `${major}.${minor}.${patch}`;
  return prerelease ? `${base}-${prerelease}` : base;
}

function bump(version, level) {
  const v = parse(version);
  if (level === 'major') {
    return format({ major: v.major + 1, minor: 0, patch: 0, prerelease: null });
  }
  if (level === 'minor') {
    return format({ major: v.major, minor: v.minor + 1, patch: 0, prerelease: null });
  }
  if (level === 'patch') {
    return format({ major: v.major, minor: v.minor, patch: v.patch + 1, prerelease: null });
  }
  throw new Error(`Unknown bump level: ${level}`);
}

function readVersion(pluginRoot) {
  return fs.readFileSync(path.join(pluginRoot, 'VERSION'), 'utf8').trim();
}

function writeVersion(pluginRoot, version) {
  parse(version); // validate
  fs.writeFileSync(path.join(pluginRoot, 'VERSION'), `${version}\n`);
}

// The shields.io version badge embedded in every README. The badge value is a
// version marker that MUST equal VERSION (knowledge/bump-protocol.md).
const BADGE_RE = /version-\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?-green\.svg/g;

// Every README that carries the version badge: the root README + one per locale
// under docs/<locale>/. Returns repo-relative paths that exist.
function readmeBadgeFiles(pluginRoot) {
  const files = ['README.md'];
  const docsDir = path.join(pluginRoot, 'docs');
  if (fs.existsSync(docsDir)) {
    for (const e of fs.readdirSync(docsDir, { withFileTypes: true })) {
      if (e.isDirectory() && fs.existsSync(path.join(docsDir, e.name, 'README.md'))) {
        files.push(`docs/${e.name}/README.md`);
      }
    }
  }
  return files.filter(f => fs.existsSync(path.join(pluginRoot, f)));
}

// The version pill string inside the authored hero SVG (assets/hero.svg). The pill
// reads `vX.Y.Z · Mon YYYY`; only the version segment is a marker (the month is
// regenerated by build-hero). Returns null when there is no hero SVG.
function heroPillVersion(pluginRoot) {
  const svg = path.join(pluginRoot, 'assets', 'hero.svg');
  if (!fs.existsSync(svg)) {
    return null;
  }
  const m = fs.readFileSync(svg, 'utf8').match(/>v(\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?)\s*(?:·|&#183;|&middot;)/);
  return m ? m[1] : null;
}

// Fan VERSION out to ALL version markers (the canonical bump-target list lives in
// knowledge/bump-protocol.md): the two .claude-plugin manifests, the root
// package.json, and every README version badge. The hero pill is NOT string-patched
// here — it is regenerated by assets/build-hero.js (which derives the pill from
// VERSION) after the sync. Returns the list of files rewritten.
function sync(pluginRoot) {
  const version = readVersion(pluginRoot);
  const jsonTargets = [
    { file: '.claude-plugin/plugin.json', apply: (j) => { j.version = version; } },
    {
      file: '.claude-plugin/marketplace.json',
      apply: (j) => {
        if (Array.isArray(j.plugins) && j.plugins[0]) {
          j.plugins[0].version = version;
        }
      },
    },
    { file: 'package.json', apply: (j) => { j.version = version; } },
  ];
  const written = [];
  for (const t of jsonTargets) {
    const abs = path.join(pluginRoot, t.file);
    if (!fs.existsSync(abs)) {
      continue;
    }
    const json = JSON.parse(fs.readFileSync(abs, 'utf8'));
    t.apply(json);
    fs.writeFileSync(abs, `${JSON.stringify(json, null, 2)}\n`);
    written.push(t.file);
  }
  // README badges (root + locales): idempotent text rewrite, only where present.
  const badge = `version-${version}-green.svg`;
  for (const file of readmeBadgeFiles(pluginRoot)) {
    const abs = path.join(pluginRoot, file);
    const content = fs.readFileSync(abs, 'utf8');
    if (BADGE_RE.test(content)) {
      const next = content.replace(BADGE_RE, badge);
      if (next !== content) {
        fs.writeFileSync(abs, next);
        written.push(file);
      }
    }
  }
  return { version, written };
}

// Check that every derived version marker agrees with VERSION (no drift). Covers
// the two manifests, package.json, every README badge, and the hero pill.
function checkSync(pluginRoot) {
  const version = readVersion(pluginRoot);
  const drift = [];
  const jsonChecks = [
    { file: '.claude-plugin/plugin.json', get: (j) => j.version },
    { file: '.claude-plugin/marketplace.json', get: (j) => j.plugins && j.plugins[0] && j.plugins[0].version },
    { file: 'package.json', get: (j) => j.version },
  ];
  for (const c of jsonChecks) {
    const abs = path.join(pluginRoot, c.file);
    if (!fs.existsSync(abs)) {
      continue;
    }
    const got = c.get(JSON.parse(fs.readFileSync(abs, 'utf8')));
    if (got !== version) {
      drift.push({ file: c.file, expected: version, got });
    }
  }
  const badge = `version-${version}-green.svg`;
  for (const file of readmeBadgeFiles(pluginRoot)) {
    const content = fs.readFileSync(path.join(pluginRoot, file), 'utf8');
    const m = content.match(/version-(\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?)-green\.svg/);
    if (m && m[0] !== badge) {
      drift.push({ file: `${file} (badge)`, expected: version, got: m[1] });
    }
  }
  const pill = heroPillVersion(pluginRoot);
  if (pill !== null && pill !== version) {
    drift.push({ file: 'assets/hero.svg (pill)', expected: version, got: pill });
  }
  return { ok: drift.length === 0, version, drift };
}

module.exports = {
  parse, format, bump, readVersion, writeVersion, sync, checkSync,
  readmeBadgeFiles, heroPillVersion,
};
