'use strict';
// Discovery loader for global-plugins. Generated by engine/build-opencode.js.
// Re-exports the plugin entry from this plugin's private bundle so OpenCode's
// plugins/ auto-discovery finds it without the compiled code leaving the bundle.
module.exports = { GlobalPluginsPlugin: require('../_global-plugins/dist/index').GlobalPluginsPlugin };
